language: python
script: python manage.py migrate
before-install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install black
script:
  - flake8 --max-line-length=130 --ignore=F405,F403,F541,W503,E231
  - black .
  - black --check .
  - cd food_redistribution
  - coverage run --source="." manage.py test accounts
  - coverage run --source="." manage.py test cal
  - coverage run --source="." manage.py test yelp_search.tests.test_views

after_success:
  - coveralls
